import type { Agent, PolicyRule, TimeSeriesData } from "@/lib/types";

export const agents: Agent[] = [
  {
    id: "agent-001",
    name: "Data-Processor-Alpha",
    status: "running",
    taskQueueLength: 12,
    currentObjective: "Analyze market sentiment from news feeds",
    confidence: 0.92,
    cpuUsage: 78,
    memoryUsage: 65,
    networkIO: { in: 120, out: 45 },
    tokenUsage: 60,
  },
  {
    id: "agent-002",
    name: "Web-Crawler-Beta",
    status: "running",
    taskQueueLength: 5,
    currentObjective: "Scrape e-commerce sites for pricing data",
    confidence: 0.88,
    cpuUsage: 55,
    memoryUsage: 80,
    networkIO: { in: 800, out: 150 },
    tokenUsage: 82,
  },
  {
    id: "agent-003",
    name: "Image-Classifier-Gamma",
    status: "idle",
    taskQueueLength: 0,
    currentObjective: "Awaiting image processing jobs",
    confidence: 0.99,
    cpuUsage: 5,
    memoryUsage: 20,
    networkIO: { in: 2, out: 1 },
    tokenUsage: 15,
  },
  {
    id: "agent-004",
    name: "Code-Generator-Delta",
    status: "errored",
    taskQueueLength: 1,
    currentObjective: "Generate boilerplate for new microservice",
    confidence: 0.34,
    cpuUsage: 95,
    memoryUsage: 92,
    networkIO: { in: 10, out: 5 },
    tokenUsage: 98,
  },
  {
    id: "agent-005",
    name: "Orchestrator-Epsilon",
    status: "running",
    taskQueueLength: 2,
    currentObjective: "Manage and distribute tasks to worker agents",
    confidence: 0.95,
    cpuUsage: 30,
    memoryUsage: 40,
    networkIO: { in: 250, out: 300 },
    tokenUsage: 35,
  },
    {
    id: "agent-006",
    name: "Log-Analyzer-Zeta",
    status: "stopped",
    taskQueueLength: 0,
    currentObjective: "Manual stop by operator",
    confidence: 1.0,
    cpuUsage: 0,
    memoryUsage: 10,
    networkIO: { in: 0, out: 0 },
    tokenUsage: 5,
  },
];

export const policies: PolicyRule[] = [
  {
    id: "policy-01",
    condition: "CPU_USAGE > 80% AND MEMORY_USAGE > 75%",
    action: "SCALE_AGENT_UP",
    priority: 10,
    description: "Scale up agent resources when both CPU and Memory are under heavy load.",
    createdBy: "user",
  },
  {
    id: "policy-02",
    condition: "SUCCESS_RATE < 90%",
    action: "SEND_ALERT_TO_SLACK",
    priority: 50,
    description: "Notify the on-call team if the task success rate drops below 90%.",
    createdBy: "user",
  },
    {
    id: "policy-03",
    condition: "TASK_QUEUE_LENGTH > 100",
    action: "RESTART_AGENT",
    priority: 25,
    description: "Restart agent if the task queue grows excessively, indicating a potential stall.",
    createdBy: "ai",
  },
];

export const telemetryData: TimeSeriesData[] = [
  { time: '12:00', cpu: 22, memory: 45 },
  { time: '12:05', cpu: 35, memory: 48 },
  { time: '12:10', cpu: 45, memory: 50 },
  { time: '12:15', cpu: 38, memory: 52 },
  { time: '12:20', cpu: 52, memory: 60 },
  { time: '12:25', cpu: 68, memory: 65 },
  { time: '12:30', cpu: 75, memory: 70 },
  { time: '12:35', cpu: 60, memory: 68 },
  { time: '12:40', cpu: 55, memory: 66 },
  { time: '12:45', cpu: 70, memory: 72 },
  { time: '12:50', cpu: 82, memory: 80 },
  { time: '12:55', cpu: 78, memory: 75 },
];
